"""
Software for the paper "When Does Known Input Covariance Help Least Squares? A Closed-Form Analysis"
by J. Arenas-Garcia, C. Moriana Varo, L. K. Hansen, and J. Larsen.

The SW produces the figures included in the paper, and allow exploration of other settings

- Figure 1: closed-form EMSE of the LS and SS estimators, the cross-EMSE,
  and the EMSE of the optimal combination, shown as solid lines.  Monte Carlo
  estimates are overlaid as markers. For the combination, the markers
  correspond to the *realized* estimator with leave-one-out (LOO) estimation
  of the mixing parameter
  
- Figure 2: theoretical optimal mixing parameter lambda (solid line), 
  together with the mean of the LOO estimate (markers) and a shaded band
  of +/- one standard deviation

Model:  y = w_o^T x + e,  x ~ N(0, Sigma),  e ~ N(0, sigma_e^2),  N > M.
"""

from __future__ import annotations

import numpy as np
import matplotlib.pyplot as plt
from matplotlib import rcParams

try:
    from tqdm import tqdm
except ImportError:
    def tqdm(x, **kwargs):
        return x

# =============================================================================
# Figure Style
# =============================================================================
def set_style():
    rcParams.update({
        "font.family": "serif",
        "font.size": 9,
        "axes.labelsize": 10,
        "axes.titlesize": 10,
        "legend.fontsize": 6.5,
        "xtick.labelsize": 8.5,
        "ytick.labelsize": 8.5,
        "lines.linewidth": 1.7,
        "axes.linewidth": 0.8,
        "axes.edgecolor": "#444444",
        "axes.grid": True,
        "grid.color": "#cccccc",
        "grid.linewidth": 0.5,
        "grid.alpha": 0.7,
        "axes.axisbelow": True,
        "figure.dpi": 130,
        "savefig.dpi": 300,
        "savefig.bbox": "tight",
        "legend.frameon": True,
        "legend.framealpha": 0.92,
        "legend.edgecolor": "#bbbbbb",
    })


# Colour palette (colour-blind friendly, modern)
COL = {
    "ls":    "#0072B2",   # blue
    "ss":    "#D55E00",   # vermillion
    "cross": "#009E73",   # green
    "comb":  "#000000",   # black
    "loo":   "#CC79A7",   # purple
    "band":  "#0072B2",   # band colour for Fig. 2
}


# =============================================================================
# Closed-form EMSE expressions (Section III of the paper)
# =============================================================================
def emse_ls(M, N, sigma_e2):
    return M * sigma_e2 / (N - M - 1)


def emse_ss(M, N, wSw, sigma_e2):
    return (M + 1) / N * wSw + M * sigma_e2 / N


def cross_emse(M, N, sigma_e2):
    return M * sigma_e2 / N


def lambda_opt(xi_ls, xi_ss, xi_cr):
    return (xi_ss - xi_cr) / (xi_ls + xi_ss - 2.0 * xi_cr)


def emse_comb_opt(xi_ls, xi_ss, xi_cr):
    return (xi_ls * xi_ss - xi_cr**2) / (xi_ls + xi_ss - 2.0 * xi_cr)


# =============================================================================
# Input covariance and model vector wo
# =============================================================================
def build_covariance(M, colouring):
    """Return the M x M input covariance matrix.

    "white"       -> identity
    ("ar1", a)    -> Toeplitz covariance of an AR(1) process generated by the
                     IIR filter H(z) = sqrt(1-a^2)/(1-a z^-1) driven by white
                     noise, i.e. Sigma_ij = a^|i-j|, with trace(Sigma)/M = 1

    Note that the colored input model has been adjusted so that the trace of
    the matrix is the same as for the white input model
    """
    
    if colouring == "white":
        return np.eye(M)
        
    if isinstance(colouring, (tuple, list)) and colouring[0] == "ar1":
        a = float(colouring[1])
        if not -1.0 < a < 1.0:
            raise ValueError("AR(1) parameter a must satisfy |a| < 1")
        idx = np.arange(M)
        return a ** np.abs(idx[:, None] - idx[None, :])
        
    raise ValueError(f"unknown colouring specification: {colouring!r}")


def build_w_o(Sigma, w_norm, alignment, k, rng):
    """Construct the unknown vector w_o with indicated norm and alignment

    alignment = "random" -> generic random direction
    alignment = "low"    -> w_o spread over the k eigenvectors of Sigma with
                            the smallest eigenvalues
    alignment = "high"   -> w_o spread over the k eigenvectors of Sigma with
                            the largest eigenvalues

    For "low"/"high", w_o is a random combination of the selected
    eigenvectors, so it lies exactly in the chosen eigen-subspace
    """
    
    M = Sigma.shape[0]
    
    if alignment == "random":
        w = rng.standard_normal(M)
        return w_norm * w / np.linalg.norm(w)

    #Compute eigenvectors and eigenvalues in ascending order
    eigvals, eigvecs = np.linalg.eigh(Sigma)
    if alignment == "low":
        sel = eigvecs[:, :k]
    elif alignment == "high":
        sel = eigvecs[:, -k:]
    else:
        raise ValueError(f"unknown alignment: {alignment!r}")

    coeff = rng.standard_normal(sel.shape[1])
    w = sel @ coeff
    return w_norm * w / np.linalg.norm(w)


# =============================================================================
# Functions of data generation and computing the LS and SS estimators
# =============================================================================
def generate_dataset(N, w_o, Sigma_chol, sigma_e, rng):
    M = w_o.size
    X = Sigma_chol @ rng.standard_normal((M, N))
    y = X.T @ w_o + sigma_e * rng.standard_normal(N)
    return X, y


def estimator_ls(X, y):
    return np.linalg.solve(X @ X.T, X @ y)


def estimator_ss(X, y, Sigma_inv):
    N = X.shape[1]
    return (1.0 / N) * Sigma_inv @ X @ y


# =============================================================================
# LOO estimation of the mixing parameter (Section IV)
# =============================================================================
def loo_residuals(X, y, Sigma_inv):
    """This function calculates, given the data and the inverse autocovariance
    of the input samples the residuals of all the samples in the training set
    using a LOO strategy, i.e., for each sample the model is trained on the rest
    of the training set, and the residual for that specific sample is calculated

    All residuals can be calculated at without retraining the model using the
    standard closed-form LOO identity based on the leverage scores. In this way,
    the cost is reduced from O(N M^3) to O(M^3 + M^2 N)
    """
    M, N = X.shape
    XXT_inv = np.linalg.inv(X @ X.T)
    w_ls = XXT_inv @ (X @ y)
    resid_in = y - X.T @ w_ls
    leverage = np.einsum("in,ij,jn->n", X, XXT_inv, X)
    e_ls = resid_in / (1.0 - leverage)

    Xy = X @ y
    xT_SigInv_Xy = X.T @ (Sigma_inv @ Xy)
    xT_SigInv_x = np.einsum("in,in->n", X, Sigma_inv @ X)
    y_pred_ss = (xT_SigInv_Xy - xT_SigInv_x * y) / (N - 1)
    e_ss = y - y_pred_ss
    return e_ls, e_ss


def estimate_lambda_loo(X, y, Sigma_inv):
    """LOO estimate of the mixing parameter
    
    This estimate is based on MSE values, which is equivalent to the EMSE based
    formula which is available in the paper

    We add clipping to the interval [0,1], as theory shows that the optimal
    mixing parameter lies in that interval
    """    
    e_ls, e_ss = loo_residuals(X, y, Sigma_inv)
    mse_ls = np.mean(e_ls**2)
    mse_ss = np.mean(e_ss**2)
    mse_cr = np.mean(e_ls * e_ss)
    denom = mse_ls + mse_ss - 2.0 * mse_cr
    if abs(denom) < 1e-12:
        return 0.5
    return float(np.clip((mse_ss - mse_cr) / denom, 0.0, 1.0))


# =============================================================================
# Monte Carlo sweep
# =============================================================================
def monte_carlo(M, w_o, Sigma, sigma_e2, N_markers, n_runs, seed):
    """Run the Monte Carlo simulation at the marker locations N_markers.

    Returns a dict that contains, for each N: the empirical EMSE of LS,
    SS, cross-EMSE, and EMSE of the LOO combination; plus the mean and
    std of the LOO mixing parameter.
    """
    rng = np.random.default_rng(seed)
    Sigma_inv = np.linalg.inv(Sigma)
    Sigma_chol = np.linalg.cholesky(Sigma)
    sigma_e = np.sqrt(sigma_e2)

    out = {key: np.empty(len(N_markers))
           for key in ("ls", "ss", "cross", "loo", "lam_mean", "lam_std")}

    for j, N in enumerate(tqdm(N_markers, desc="Sweeping N", unit="N")):
        acc_ls = acc_ss = acc_cr = acc_loo = 0.0
        lam_samples = np.empty(n_runs)

        #Monte Carlo estimation of errors and lambda
        for r in range(n_runs):

            #Create data for the Monte Carlo run
            X, y = generate_dataset(N, w_o, Sigma_chol, sigma_e, rng)

            #Calculate the LS and SS estimators and their EMSEs
            #Calculate the crossEMSE as well
            w_ls = estimator_ls(X, y)
            w_ss = estimator_ss(X, y, Sigma_inv)

            d_ls = w_o - w_ls
            d_ss = w_o - w_ss
            acc_ls += float(d_ls @ Sigma @ d_ls)
            acc_ss += float(d_ss @ Sigma @ d_ss)
            acc_cr += float(d_ls @ Sigma @ d_ss)

            #Calculate LOO estimation for lambda and use that lambda
            #value to calculate the EMSE for this run
            lam = estimate_lambda_loo(X, y, Sigma_inv)
            lam_samples[r] = lam
            d_c = w_o - (lam * w_ls + (1.0 - lam) * w_ss)
            acc_loo += float(d_c @ Sigma @ d_c)

        out["ls"][j] = acc_ls / n_runs
        out["ss"][j] = acc_ss / n_runs
        out["cross"][j] = acc_cr / n_runs
        out["loo"][j] = acc_loo / n_runs
        out["lam_mean"][j] = lam_samples.mean()
        out["lam_std"][j] = lam_samples.std()
    return out


# =============================================================================
# Figure 1 -- EMSE
# =============================================================================
def figure_emse(M, N_max, w_o, Sigma, sigma_e2, mc, N_markers,
                title, save_path):
    wSw = float(w_o @ Sigma @ w_o)

    N_all = np.arange(M + 2, N_max + 1)
    
    # --- Theoretical curves calculation ---
    xi_ls = np.array([emse_ls(M, N, sigma_e2) for N in N_all])
    xi_ss = np.array([emse_ss(M, N, wSw, sigma_e2) for N in N_all])
    xi_cr = np.array([cross_emse(M, N, sigma_e2) for N in N_all])
    xi_c = np.array([emse_comb_opt(a, b, c)
                     for a, b, c in zip(xi_ls, xi_ss, xi_cr)])

    to_db = lambda v: 10.0 * np.log10(np.maximum(v, 1e-15))

    fig, ax = plt.subplots(figsize=(3.5, 2))

    # --- theoretical curves (solid) ---
    ax.plot(N_all, to_db(xi_ls), "-", color=COL["ls"], label="LS (7)")
    ax.plot(N_all, to_db(xi_ss), "-", color=COL["ss"], label="SS (8)")
    ax.plot(N_all, to_db(xi_cr), "-", color=COL["cross"],
            label="cross-EMSE (11)")
    ax.plot(N_all, to_db(xi_c), "-", color=COL["comb"],
            label="Combination (13)")

    # --- Monte Carlo markers ---
    mk = dict(linestyle="none", markersize=4.5, markeredgewidth=0.7)
    ax.plot(N_markers, to_db(mc["ls"]), marker="o",
            markerfacecolor="none", markeredgecolor=COL["ls"], label="LS simu", **mk)
    ax.plot(N_markers, to_db(mc["ss"]), marker="s",
            markerfacecolor="none", markeredgecolor=COL["ss"], label="SS simu", **mk)
    ax.plot(N_markers, to_db(mc["cross"]), marker="^",
            markerfacecolor="none", markeredgecolor=COL["cross"], label="cross-EMSE simu", **mk)
    ax.plot(N_markers, to_db(mc["loo"]), marker="D",
            markerfacecolor=COL["loo"], markeredgecolor=COL["loo"],
            markersize=3.8, linestyle="none",
            label="Combination (LOO)")

    ax.set_xlabel(r"Training set size $N$")
    #ax.set_xticklabels([])
    ax.set_ylabel("EMSE (dB)")
    if title:
        ax.set_title(title)
    ax.set_xlim(M, N_max)
    ax.legend(ncol=2, loc="best")
    fig.tight_layout()
    if save_path is None:
        plt.show()
    else:
        fig.savefig(save_path)
        plt.close(fig)
        print(f"saved: {save_path}")


# =============================================================================
# Figure 2 -- mixing parameter
# =============================================================================
def figure_lambda(M, N_max, w_o, Sigma, sigma_e2, mc, N_markers,
                   title, save_path):
    wSw = float(w_o @ Sigma @ w_o)

    # --- Calculate theoretical lambda ---
    N_all = np.arange(M + 2, N_max + 1)
    lam_all = np.array([
        lambda_opt(emse_ls(M, N, sigma_e2),
                   emse_ss(M, N, wSw, sigma_e2),
                   cross_emse(M, N, sigma_e2))
        for N in N_all])

    # wider, shorter aspect ratio
    fig, ax = plt.subplots(figsize=(3.5, 1.5))

    ax.plot(N_all, lam_all, "-", color=COL["comb"],
            label=r"$\lambda^*$ (optimal)")

    ax.fill_between(N_markers,
                    mc["lam_mean"] - mc["lam_std"],
                    mc["lam_mean"] + mc["lam_std"],
                    color=COL["band"], alpha=0.18, linewidth=0)
    ax.plot(N_markers, mc["lam_mean"], marker="o", linestyle="none",
            markersize=4.5, markerfacecolor=COL["band"],
            markeredgecolor="white", markeredgewidth=0.6,
            label=r"$\widehat{\lambda}$ (LOO)")

    ax.set_xlabel(r"Training set size $N$")
    ax.set_ylabel(r"$\lambda$")
    if title:
        ax.set_title(title)
    ax.set_xlim(M, N_max)
    ax.set_ylim(-0.05, 1.08)
    ax.legend(loc="best", ncol=2)
    fig.tight_layout()
    if save_path is None:
        plt.show()
    else:
        fig.savefig(save_path)
        plt.close(fig)
        print(f"saved: {save_path}")


# =============================================================================
# Main entry point
# =============================================================================
def make_figures(M=96, N_max=480, n_runs=500, w_norm=1.0, noise_power=0.1,
                 colouring="white", alignment="random", k=1,
                 marker_step=10, seed=0, show_title=True,
                 fig1_path=None, fig2_path=None):
    """Generate the EMSE figure and the mixing-parameter figure.

    Parameters
    ----------
    M            : dimension of w_o
    N_max        : largest training-set size shown
    n_runs       : number of Monte Carlo training sets
    w_norm       : Euclidean norm of w_o
    noise_power  : observation-noise variance sigma_e^2
    colouring    : "white" or ("ar1", a)
    alignment    : "random", "low" or "high" -- alignment of w_o with the
                   eigenvectors of Sigma
    k            : number of eigenvectors used when alignment is "low"/"high"
    marker_step  : spacing in N between Monte Carlo markers
    seed         : RNG seed
    show_title   : whether to draw an informative title
    fig1_path,
    fig2_path    : output files
    """
    set_style()
    sigma_e2 = float(noise_power)

    rng = np.random.default_rng(seed)
    Sigma = build_covariance(M, colouring)
    w_o = build_w_o(Sigma, w_norm, alignment, k, rng)

    N_markers = np.arange(M + 3, N_max + 1, marker_step)

    mc = monte_carlo(M, w_o, Sigma, sigma_e2, N_markers, n_runs, seed + 1)

    if show_title:
        colour_label = ("white" if colouring == "white"
                        else f"AR(1) $a={colouring[1]:g}$")
        align_label = (alignment if alignment == "random"
                       else f"{alignment}-$k{k}$")
        title = (rf"$M={M}$, $\sigma_\epsilon^2={sigma_e2:g}$, "
                 rf"{colour_label}, {align_label}")
    else:
        title = None

    figure_emse(M, N_max, w_o, Sigma, sigma_e2, mc, N_markers,
                title, fig1_path)
    figure_lambda(M, N_max, w_o, Sigma, sigma_e2, mc, N_markers,
                  title, fig2_path)


if __name__ == "__main__":
    # AR(1) regressors, sigma_eps_2=0.5
    make_figures(M=64, N_max=200, n_runs=1000, w_norm=1.0, noise_power=0.5,
                 colouring=('ar1',0.9), alignment="random", k=1,
                 marker_step=13, seed=42, show_title=False,
                 fig1_path="EMSE_AR1_eps05.pdf", fig2_path="lambda_AR1_eps05.pdf")
    # AR(1) regressors, sigma_eps_2=0.1
    make_figures(M=64, N_max=160, n_runs=1000, w_norm=1.0, noise_power=0.1,
                 colouring=('ar1',0.9), alignment="random", k=1,
                 marker_step=10, seed=42, show_title=False,
                 fig1_path="EMSE_AR1_eps01.pdf", fig2_path="lambda_AR1_eps01.pdf")
    # AR(1) regressors, sigma_eps_2=0.1, aligned in small eigenvalues subspace
    make_figures(M=64, N_max=270, n_runs=1000, w_norm=1.0, noise_power=0.1,
                 colouring=('ar1',0.8), alignment="low", k=16,
                 marker_step=25, seed=42, show_title=False,
                 fig1_path="EMSE_AR1_eps01_low.pdf", fig2_path="lambda_AR1_eps01_low.pdf")

    print("done.")
    